Changed self extracting archive extention to ".sh".
The self extracting shell archive format has been renamed .sh
(from the previous .bin). The .bin format now falls back to .sh.

Fixes #203

diff --git a/modules/stubbs/commands/archive/script b/modules/stubbs/commands/archive/script
--- a/modules/stubbs/commands/archive/script
+++ b/modules/stubbs/commands/archive/script
@@ -1,7 +1,7 @@
 #!/usr/bin/env bash
 #
 # command: stubbs:archive: "Build a self extracting archive"
-#/ usage: rerun stubbs:archive [ --file|-f <>] [ --format|-f <bin>]  --modules <'*'> [ --release <1>] [ --version <>] [ --template <>]
+#/ usage: rerun stubbs:archive [ --file|-f <>] [ --format|-f <sh>]  --modules <'*'> [ --release <1>] [ --version <>] [ --template <>]
 
 
 # Load common functions
@@ -94,16 +94,16 @@ encode() {
     return $retval
 }
 
-build_bin_archive() {
+build_sh_archive() {
   CWD=$(pwd); #remember current working directory.
 
-  # Check if file option was specified and if not set it to rerun.bin.
-  [[ -z "${FILE:-}"  ]] && FILE=rerun.bin
+  # Check if file option was specified and if not set it to rerun.sh.
+  [[ -z "${FILE:-}"  ]] && FILE=rerun.sh
 
   # Prepend current working directory if relative file path.
   [[ ${FILE} == "/"* ]] || FILE=$CWD/$FILE
 
-  [[ ! -d $(dirname ${FILE}) ]] && rerun_option_error "directory not found: $(dirname ${FILE})"
+  [[ ! -d $(dirname ${FILE}) ]] && { echo >&2 "directory not found: $(dirname ${FILE})"; exit 2; }
 
   # create a work directory the archive content
   export PAYLOAD=`mktemp -d /tmp/rerun.stubbs.archive.XXXXXX` || rerun_die
@@ -401,8 +401,8 @@ build_rpm_archive() {
 
 
 case $FORMAT in
-  bin)
-    build_bin_archive
+  bin|sh)
+    build_sh_archive
     ;;
   deb)
     build_deb_archive
diff --git a/modules/stubbs/templates/extract b/modules/stubbs/templates/extract
--- a/modules/stubbs/templates/extract
+++ b/modules/stubbs/templates/extract
@@ -1,6 +1,7 @@
 #!/usr/bin/env bash
 #
-# extract - this is a self contained self extracting rerun 
+# @FILE@ - This is a self extracting archive. 
+#
 #
 # generator: @GENERATOR@
 # decoder: @DECODER@
@@ -8,7 +9,7 @@
 # user: @USER@
 # archive-version: @VERSION@
 # archive-release: @RELEASE@
-#/ usage: @FILE@ [--archive-version-release] [--extract-only|-N <>] [--extract-dir|-D <>] [args]
+#/ usage: @FILE@ [--archive-version-release] [--extract-only|-N <>] [--extract-dir|-D <>] [module]:[command] [options]
 
 
 # Function to print error message and exit.
@@ -51,16 +52,16 @@ umask 0002
 # If it is unset, create a temporary directory.
 if [[ -z "${EXTRACT_DIR}" ]]
 then
-    SCRATCH_FILES[0]=`mktemp -d ${TMPDIR}/rerun.bin.XXXXXX` || die "failed creating temporary directory."
+    SCRATCH_FILES[0]=$(mktemp -d ${TMPDIR}/rerun.bin.XXXXXX) || die "failed creating temporary directory."
     EXTRACT_DIR=${SCRATCH_FILES[0]}
 else
     mkdir -p "$EXTRACT_DIR"
 fi
 export PAYLOAD=${EXTRACT_DIR}
 
-# CWD and oldCWD are passed to launcher as env variables.
-export oldCWD=$(pwd)
-export CWD=/tmp
+# CWD is passed to launcher as an environment variable.
+
+export CWD=$(pwd)
 
 # Extraction time!
 # - read lines from delimiter and pass to tar unarchive
@@ -76,16 +77,12 @@ if [[ -n "$EXTRACT_ONLY" ]]
 then exit $? 
 fi
 
-
-# Change directory to the payload directory.
-cd $EXTRACT_DIR || die "Could not change directory to payload."
-
+#
 # Run the launcher !
-bash ./launcher "$@"
+#
+bash $EXTRACT_DIR/launcher "$@"
 RETVAL=$?
 
-# Go back to original working directory
-cd $oldCWD
 
 # Stop this script from executing before we reach the binary archive!
 exit ${RETVAL:=0}
