added creation of "latest" symlink to last replay log.

diff --git a/rerun b/rerun
--- a/rerun
+++ b/rerun
@@ -265,9 +265,16 @@ then
     #
 	if [ -n "$RERUN_LOGS" -a -d "$RERUN_LOGS" ]
 	then
-	    # set up a replay log file
-		TSTAMP=$(date '+%Y-%m-%dT%H%M%S')
-		LOG=$RERUN_LOGS/$MODULE-$COMMAND-$TSTAMP.running
+	    # set up the log file
+		TSTAMP=$(date '+%Y-%m-%dT%H%M%S-%Z')
+		LOG=$RERUN_LOGS/$MODULE-$COMMAND-$TSTAMP-$$.running
+		#
+		# Execute the command script
+		#
+	    $SH $VERBOSE $CMD_SCRIPT "$@" | tee -a $LOG
+	    EXIT_STATUS=$?
+		
+		# Generate replay metadata
 		(
 		cat <<-EOF
 		#
@@ -279,13 +286,23 @@ then
 		OPTIONS="$*"
 		USER="$USER"
 		DATE="$TSTAMP"
+		EXIT_STATUS="$EXIT_STATUS"
 		__LOG_BELOW__
 
 		EOF
-		) > $LOG
-	    $SH $VERBOSE $CMD_SCRIPT "$@" | tee -a $LOG
-		mv $LOG $RERUN_LOGS/$MODULE-$COMMAND-$TSTAMP.replay || die
+		) > ${LOG%*.running}.metadata || die
+		
+		#
+		# Generate .replay
+		cat ${LOG%*.running}.metadata $LOG > $RERUN_LOGS/$MODULE-$COMMAND-$TSTAMP.replay || die		
+		rm -f $LOG ${LOG%*.running}.metadata; # cleanup working files
+		# New log
 		LOG=$RERUN_LOGS/$MODULE-$COMMAND-$TSTAMP.replay
+		
+		# Reset the "latest" symlink
+		rm -f $RERUN_LOGS/$MODULE-$COMMAND-latest.replay; #remove old symlink
+		ln -s $LOG $RERUN_LOGS/$MODULE-$COMMAND-latest.replay; # recreate it
+		
 		if [ -n "$REPLAY" ]
 		then
 			# extract the log content from checklog
