Added new flag called "--answers <>" that lets users specify option values from a file. Fixes #23 Also changed execution logic to exec command scripts if they are executable. Fixes #21

diff --git a/rerun b/rerun
--- a/rerun
+++ b/rerun
@@ -21,7 +21,7 @@ SH="/usr/bin/env bash"
 # Save the name of the rerun executable to show in usage messages.
 PROG=$(basename $0)
 USAGE="
-Usage: $PROG [-h][-v][-V] [-M <dir>] [-L <dir>] [--replay <file>] [module:[command [options]]]
+Usage: $PROG [-h][-v][-V] [-M <dir>] [-L <dir>] [--replay <file>] [--answer <file>] [module:[command [options]]]
 "
 PAD="  "
 
@@ -86,14 +86,11 @@ man() {
     local module=$1
     if [ ! -f "$RERUN_MODULES/$module/$module.1" \
            -a -f "$RERUN_MODULES/stubbs/commands/docs/default.sh" ]
-    then
-       $RERUN stubbs:docs --module $module 
+    then $RERUN stubbs:docs --module $module 
     fi
     if [ -f "$RERUN_MODULES/$module/$module.1" ]
-    then
-        nroff -man "$RERUN_MODULES/$module/$module.1" | ${PAGER:-more}
-    else
-        echo "Manual could not be generated." >&2
+    then nroff -man "$RERUN_MODULES/$module/$module.1" | ${PAGER:-more}
+    else echo "Manual could not be generated." >&2
     fi
 }
 
@@ -136,10 +133,8 @@ rerun_resolveCommandScript() {
     local command_dir=$module_dir/commands/${command}
     local os=$(uname -s)
     if [ -f  "$command_dir/${os}.sh" ]
-    then
-        echo $command_dir/${os}.sh; 
-    else
-        echo $command_dir/default.sh; 
+    then echo $command_dir/${os}.sh; 
+    else echo $command_dir/default.sh; 
     fi
 }
 
@@ -212,6 +207,30 @@ EOF
     )
 }
 
+# given a command set options based on answer file
+answerOptions() {
+    [ $# -lt 2 ] && {
+        echo "usage: answerOptions: module command ?answers?" >&2
+        return 2
+    }
+    argline=
+    for metadata in $RERUN_MODULES/$1/commands/$2/*.option
+    do        
+        option=$(
+            . $metadata; # source the option metadata
+            [ -n "$LONG" ] && flag="$LONG" || flag="$NAME"
+            if [ "$ARGUMENTS" = "true" -a -r "$3" ]
+            then 
+                var=$(echo $NAME | tr "[a-z]" "[A-Z]")
+                arg=$(awk -F= "/^$var/ {print \$2}" $3)
+            fi
+            [ -n "$arg" ] && printf -- "--%s %s" "$flag" "$arg"
+        )
+        argline="$argline $option"
+    done
+    echo "$argline"
+}
+
 # Option parsing
 # --------------
 
@@ -263,6 +282,12 @@ while [ "$#" -gt 0 ]; do
 	--replay)
 	    rerun_syntax_check "$#"
 	    REPLAY="$2"
+	    shift
+	    ;;	
+	--answers)
+	    rerun_syntax_check "$#"
+	    ANSWERS="$2"
+        [ ! -f $ANSWERS ] && die "answers file not found: $ANSWERS"
 	    shift
 	    ;;	
 	  # Ignore remaining arguments as they are for the module.
@@ -393,16 +418,16 @@ fi
     rerun_syntax_error command not found: \"$MODULE:$COMMAND\"
 }
 
+# Read answer file and set positional parameters from them.
+if [ -n "$ANSWERS" -a -f "$ANSWERS" ]
+then
+    set -- $(answerOptions $MODULE $COMMAND $ANSWERS)
+fi
+
 # Ready to run. Export rerun executable environment.
 export RERUN RERUN_MODULES 
-export MODULE_DIR=$RERUN_MODULES/$MODULE
 # Lookup the path to the command handler script.
 COMMAND_SCRIPT=$(rerun_resolveCommandScript $MODULE $COMMAND)
-# Source the module and command metadata.
-[ -r $MODULE_DIR/metadata ] && . $MODULE_DIR/metadata
-[ -r $MODULE_DIR/commands/${COMMAND}/metadata ] && {
-	. $MODULE_DIR/commands/${COMMAND}/metadata
-}
 
 # If the  `-L` flag is set, record execution.
 if [ -z "$RERUN_LOGS" -o ! -d "$RERUN_LOGS" ]
@@ -410,11 +435,17 @@ then
     # __Normal execution mode__
     # 
 
-    # Execute the command script. 
-    # Returns the command script's exit code as the result.
-
-    $SH $VERBOSE $COMMAND_SCRIPT "$@"	
-    RETVAL=$?
+    # Execute the command script if it is executable
+    # otherwise run it using the same interpreter as rerun.
+    # Return the command script's exit code as the result.
+    if [ -x $COMMAND_SCRIPT ] 
+    then
+        $COMMAND_SCRIPT "$@"
+        RETVAL=$?
+    else
+        $SH $VERBOSE $COMMAND_SCRIPT "$@"	
+        RETVAL=$?
+    fi
 else
     # __Recorded execution mode__
     # 
