improved code style after shellcheck analysis

diff --git a/rerun b/rerun
--- a/rerun
+++ b/rerun
@@ -90,7 +90,7 @@ rerun_color() {
     shift;
     local message="$*"
     if [[ -n "${RERUN_COLOR:-}" ]]
-    then echo -ne ${code}"${message:-}"${reset}
+    then echo -ne "${code}" "${message:-}" "${reset}"
     else printf -- "%s" "${message:-}"
     fi
 }    
@@ -116,9 +116,9 @@ rerun_color() {
 # * RERUN_LOG_LEVELS defines the set of valid log levels 
 RERUN_LOG_LEVELS=([0]=debug [1]=info [2]=warn [3]=error [4]=fatal)
 # * RERUN_LOG_LEVEL specifies the current log level (default: info)
-: ${RERUN_LOG_LEVEL:=1}
+: "${RERUN_LOG_LEVEL:=1}"
 # * RERUN_LOG_ERR_LEVEL specifies the minimum level for messages printed to stderr.
-: ${RERUN_LOG_ERR_LEVEL:=3}
+: "${RERUN_LOG_ERR_LEVEL:=3}"
 # * Messages can be colored depending on level.
 RERUN_LOG_COLORS=([0]=cyan [1]=green [2]=yellow [3]=red [4]=hred)
 # * RERUN_LOG_FMT_CONSOLE specifies the format for messages printed to the console.
@@ -130,7 +130,7 @@ then
     fi
 fi    
 # * RERUN_LOG_FMT_LOGFILE specifies the format for log entries.
-: ${RERUN_LOG_FMT_LOGFILE:="[%tstamp%] [%level%] %command%: %message%"}
+: "${RERUN_LOG_FMT_LOGFILE:=[%tstamp%] [%level%] %command%: %message%}"
 
 #
 rerun_log_puts() {
@@ -138,17 +138,17 @@ rerun_log_puts() {
         printf >&2 'wrong # args: should be: rerun_log_puts format level command message\n'
         return 2
     }
-    [[ "$2" =~ [0-9]+ ]] || { printf >&2 "rerun_log_puts: level must be numeric: '$2'\n"; return 2; }
+    [[ "$2" =~ [0-9]+ ]] || { printf >&2 "rerun_log_puts: level must be numeric: '%s'\n" "$2"; return 2; }
     local -r format="$1" level="$2" command="$3" message="$4"
     local -r tstamp=$(date '+%Y-%m-%dT%H%M%S-%Z') 
-    local fmt_spec=
+    local fmt_spec output
     case "$format" in
         console) fmt_spec=$RERUN_LOG_FMT_CONSOLE
         ;;
         logfile) fmt_spec=$RERUN_LOG_FMT_LOGFILE
         ;;
     esac
-    local output=$(printf -- "%s" "$fmt_spec" | 
+    output=$(printf -- "%s" "$fmt_spec" | 
     sed -e "s^%tstamp%^$tstamp^g" \
         -e "s^%level%^${RERUN_LOG_LEVELS[$level]}^g" \
         -e "s^%command%^$command^g" \
@@ -157,10 +157,10 @@ rerun_log_puts() {
     if (( level >= RERUN_LOG_ERR_LEVEL ))
     then
         # write message to stderr
-        printf >&2 -- "%s\n" "$(rerun_color ${RERUN_LOG_COLORS[$level]} "$output")"
+        printf >&2 -- "%s\n" "$(rerun_color "${RERUN_LOG_COLORS[$level]}" "$output")"
     else
         # write message to stdout
-        printf -- "%s\n" "$(rerun_color ${RERUN_LOG_COLORS[$level]} "$output")"
+        printf -- "%s\n" "$(rerun_color "${RERUN_LOG_COLORS[$level]}" "$output")"
     fi
 
     return 0
@@ -233,7 +233,7 @@ rerun_log_syslog() {
 # * RERUN_LOG_LEVEL should only be controlled via `rerun_log level`.
 # * RERUN_LOG_FILE should be controlled via `rerun_log logfile`.
 # * RERUN_LOG_SYSLOG specifies syslog facility. Must be set to enable syslogging (unset by default).
-: ${RERUN_LOG_SYSLOG:=}
+: "${RERUN_LOG_SYSLOG:=}"
 #
 rerun_log() {
     (( $# >= 1 )) || {
@@ -241,6 +241,7 @@ rerun_log() {
         return 2
     }
     local -r action="$1"
+    local level
     case "$action" in
         levels)
             printf "%s\n" "${RERUN_LOG_LEVELS[*]}"
@@ -249,8 +250,12 @@ rerun_log() {
         level)
             (( $# == 1 )) && printf "%s\n" "${RERUN_LOG_LEVELS[$RERUN_LOG_LEVEL]}"
             (( $# == 2 )) && { 
-                local level=$(rerun_list_index "$2" "${RERUN_LOG_LEVELS[*]}")
-                (( "$level" >= 0 && "$level" <= ${#RERUN_LOG_LEVELS[*]})) && RERUN_LOG_LEVEL=$level || { printf >&2 "rerun_log level: invalid level: $2\n"; return 2; }
+                level=$(rerun_list_index "$2" "${RERUN_LOG_LEVELS[*]}")
+                if (( "$level" >= 0 && "$level" <= ${#RERUN_LOG_LEVELS[*]})); then
+                    RERUN_LOG_LEVEL=$level
+                else 
+                    printf >&2 "rerun_log level: invalid level: %s\n" "$2"; return 2; 
+                fi
             }
             return 0
             ;;
@@ -259,13 +264,15 @@ rerun_log() {
             return 0
             ;;
         syslog)
-            (( $# == 1 )) && printf "%s\n" "${RERUN_LOG_SYSLOG}" || {
+            if (( $# == 1 )); then
+                printf "%s\n" "${RERUN_LOG_SYSLOG}"
+            else
                 [[ "$2" =~ ^[[:alnum:]]+$ ]] || {
-                    printf >&2 "rerun_log syslog: facility is not a valid name: '$2'\n"
+                    printf >&2 "rerun_log syslog: facility is not a valid name: '%s'\n" "$2"
                     return 2
                 }
                 RERUN_LOG_SYSLOG=$2
-            }
+            fi
             return 0
             ;;
         fmt-console)
@@ -277,12 +284,12 @@ rerun_log() {
             return 0
             ;;
         debug|info|warn|error|fatal)
-            local level=$(rerun_list_index "$action" "${RERUN_LOG_LEVELS[*]}")
+            level=$(rerun_list_index "$action" "${RERUN_LOG_LEVELS[*]}")
             shift
             local message="$*"
             ;;
         log)
-            local level=$(rerun_list_index "$2" "${RERUN_LOG_LEVELS[*]}")
+            level=$(rerun_list_index "$2" "${RERUN_LOG_LEVELS[*]}")
             (( "$level" >= 0 && "$level" <= 4)) || { "rerun_log log: invalid level: $2"; return 2; }
             shift
             local message="$*"
@@ -298,8 +305,8 @@ rerun_log() {
     [[ -n "${RERUN_COMMAND_DIR:-}" ]] && {
         ctx=( ${ctx[*]:-} $(basename "$RERUN_COMMAND_DIR") )
     }
-    local command=$( IFS=:; printf "%s" "${ctx[*]:-}" )
-    : ${level:=$RERUN_LOG_LEVEL}
+    local -r command=$( IFS=:; printf "%s" "${ctx[*]:-}" )
+    : "${level:=$RERUN_LOG_LEVEL}"
     local current_level=$RERUN_LOG_LEVEL
     if (( level >= current_level ))
     then
@@ -485,14 +492,15 @@ rerun_modules() {
 	    rerun_die 'wrong # args: should be: rerun_modules path'
     }
     local -a modules
+    local module
     for dir in $(rerun_module_path_elements "$1")
     do
-        [[ ! -d $dir ]] && rerun_die "directory not found: $dir"
+        [[ ! -d "$dir" ]] && rerun_die "directory not found: $dir"
         for f in $dir/*/metadata
         do
-            if [[ -f $f ]]
+            if [[ -f "$f" ]]
             then 
-                local module=$(basename $(dirname "$f"))
+                module=$(basename "$(dirname "$f")")
                 [[ -z "${modules:-}" ]] && modules=( $module ) || modules=( ${modules[*]} $module )
             fi 
         done
@@ -549,14 +557,15 @@ rerun_commands() {
     (( $# == 2 )) || { 
 	    rerun_die 'wrong # args: should be: rerun_commands path module'
     }
-    local module_home=$(rerun_get_module_home_dir_in_path "$1" "$2")
+    local -r module_home=$(rerun_get_module_home_dir_in_path "$1" "$2")
     [[ -n $module_home ]] || rerun_die "module not found in path: $2 $1"
     local -a commands=()
+    local command
 	for c in $module_home/commands/*/metadata
 	do
 		if [[ -f $c ]]
 		then 
-			local command=$(basename $(dirname "$c"))
+			command=$(basename "$(dirname "$c")")
 			[[ -z "${commands:-}" ]] && commands=( $command ) || commands=( ${commands[*]} $command )
 		fi 
 	done
@@ -587,11 +596,12 @@ rerun_options() {
     (( $# == 3 )) || { 
 	    rerun_die 'wrong # args: should be: rerun_options path module command'
     }
-    local module_home=$(rerun_get_module_home_dir_in_path "$1" "$2")
+    local -r module_home=$(rerun_get_module_home_dir_in_path "$1" "$2")
     [[ -n $module_home ]] || rerun_die "module not found in path: $2 $1"
-	if [[ -f $module_home/commands/$3/metadata ]] 
+	if [[ -f "$module_home/commands/$3/metadata" ]] 
 	then
-		( .  "$module_home/commands/$3/metadata" ; echo "${OPTIONS:-}" )
+        # shellcheck source=/dev/null
+		( . "$module_home/commands/$3/metadata" ; echo "${OPTIONS:-}" )
 	else
 		echo ""
 	fi
@@ -617,14 +627,14 @@ rerun_module_options() {
     (( $# == 2 )) || { 
 	    rerun_die 'wrong # args: should be: rerun_module_options path module'
     }
-    local module_home=$(rerun_get_module_home_dir_in_path "$1" "$2")
+    local -a options=(); local option module_home    
+    module_home=$(rerun_get_module_home_dir_in_path "$1" "$2")
     [[ -n $module_home ]] || rerun_die "module not found in path: $2 $1"
-    local -a options=()
 	for o in $module_home/options/*/metadata
 	do
-		if [[ -f $o ]]
+		if [[ -f "$o" ]]
 		then 
-			local option=$(basename $(dirname "$o"))
+			option=$(basename "$(dirname "$o")")
 			[[ -z "${options:-}" ]] && options=( $option ) || options=( ${options[*]} $option )
 		fi 
 	done
@@ -924,7 +934,7 @@ rerun_module_path_elements() {
         rerun_die 'wrong # args: should be: rerun_module_path_elements path'
     }
     local path=${1}
-    echo "$path" | sed ':loop
+    sed ':loop
 {h
 s/:.*//
 p      
@@ -932,7 +942,7 @@ g
 s/[^:]*://
 t loop
 d     
-}'
+}' <<< "$path"
 
 }
 
@@ -1024,19 +1034,19 @@ rerun_command_execute() {
     RERUN_MODULE_DIR=$(rerun_module_exists "$module") || rerun_syntax_error "module not found: \"$module\""
     RERUN_COMMAND_DIR=$RERUN_MODULE_DIR/commands/$COMMAND
 
-    rerun_script_exists "${RERUN_MODULE_DIR:-}" $command || {
+    rerun_script_exists "${RERUN_MODULE_DIR:-}" "$command" || {
         rerun_syntax_error "command not found: \"$module:$command\""
     }
     local -r RERUN_SHELL=$(which bash)
-    local COMMAND_SHELL=$(rerun_property_get "$RERUN_MODULE_DIR" SHELL)
-    : ${COMMAND_SHELL:=$RERUN_SHELL}; # default it.
+    local -r COMMAND_SHELL=$(rerun_property_get "$RERUN_MODULE_DIR" SHELL)
+    : "${COMMAND_SHELL:=$RERUN_SHELL}"; # default it.
 
     if [[ -n "${SUDO_USER:-}" ]]
     then
         COMMAND_SHELL="$SUDO_COMMAND -u $SUDO_USER $COMMAND_SHELL"
     fi
 
-    local RERUN_MODULE_VERSION=$(rerun_property_get "$RERUN_MODULE_DIR" VERSION)
+    local -r RERUN_MODULE_VERSION=$(rerun_property_get "$RERUN_MODULE_DIR" VERSION)
 
     local -r script=$(rerun_script_lookup "$RERUN_MODULE_DIR" "$command")
 
@@ -1103,19 +1113,20 @@ _rerun_options_populate() {
         return 2
     }
     local -r module=$1 command=$2 answers=${3:-}
-    local module_dir=$(rerun_module_exists "$module") || rerun_syntax_error "module not found: \"$module\""
-    local argline=()
-    for cmd_option in $(rerun_options $(dirname "$module_dir") "$module" "$command")
+    local -r module_dir=$(rerun_module_exists "$module") || rerun_syntax_error "module not found: \"$module\""
+    local argline=() metadata option
+    for cmd_option in $(rerun_options "$(dirname "$module_dir")" "$module" "$command")
     do        
-        local metadata=$(dirname "$module_dir")/$module/options/$cmd_option/metadata
+        metadata=$(dirname "$module_dir")/$module/options/$cmd_option/metadata
         local varname arg argval
-        local option=$(
+        option=$(
+            # shellcheck source=/dev/null
             . "$metadata"; # source the option metadata
             [[ -n "$LONG" ]] && flag="$LONG" || flag="$NAME"
             if [[ -r "$answers" ]]
             then 
-                varname=$(echo $NAME | tr "[a-z]" "[A-Z]" | tr "-" "_")
-                arg=$(grep ^${varname}= "$answers")
+                varname=$(echo "$NAME" | tr a-z A-Z | tr "-" "_")
+                arg=$(grep "^${varname}=" "$answers")
                 argval=${arg#*=}
             fi
             [[ -n "$arg" ]] && printf -- "--%s %s" "$flag" "${argval}"
@@ -1209,14 +1220,19 @@ _rerun_module_summary() {
     (( $# != 1 )) && { 
         rerun_die "wrong # args: should be: _rerun_module_summary module_dir" 
     }
-    local -r module_dir=$1
-    local -r module_dirname=$(rerun_module_exists $(basename "$module_dir")) && {
-    local -r module_name=$(basename "$module_dir")
-    local -r module_desc=$(rerun_property_get "$module_dir" DESCRIPTION)
-    local -r module_vers=$(rerun_property_get "$module_dir" VERSION) || module_vers=""
-    printf "%s%s: \"%s\" - %s (%s)\n" "${PAD:-}" \
-        "$(rerun_color bold $module_name)" "${module_desc}" "$module_vers" "$module_dir"
-    }
+    local -r module_dir=$1 
+    local module_name module_desc module_vers
+    if rerun_module_exists "$(basename "$module_dir")"
+    then
+        module_name=$(basename "$module_dir")
+        module_desc=$(rerun_property_get "$module_dir" DESCRIPTION)
+        module_vers=$(rerun_property_get "$module_dir" VERSION) || module_vers=""
+        printf "%s%s: \"%s\" - %s (%s)\n" "${PAD:-}" \
+            "$(rerun_color yellow "$module_name")" \
+            "$(rerun_color bold "${module_desc}")" \
+            "$module_vers" \
+            "$module_dir"
+    fi
 }
 
 # __rerun_modules_summary_ - List the modules.
@@ -1235,23 +1251,24 @@ _rerun_modules_summary() {
     (( $# != 1 )) && { 
         rerun_die "wrong # args: should be: _rerun_modules_summary directory" 
     }
-    echo $(rerun_color blue "Available modules:")
+    printf "%s\n" "$(rerun_color blue "Available modules:")"
+
     shopt -s nullglob # enable
     set +u
     for directory in $(rerun_module_path_elements "$1")
     do
         for module in $directory/*
         do
-            [[ -f $module/metadata ]] && _rerun_module_summary "$module"
+            [[ -f "$module/metadata" ]] && _rerun_module_summary "$module"
         done
         if [[ ${RERUN_LOCATION:-} = "${DEFAULT_BINDIR}" 
                 && $path_element != "${DEFAULT_LIBDIR}/rerun/modules" ]]
         then
             echo
-            echo $(rerun_color blue "Available modules in \"${DEFAULT_LIBDIR}/rerun/modules\":")
+            printf "%s\n" "$(rerun_color blue "Available modules in \"${DEFAULT_LIBDIR}/rerun/modules\":")"
             for module in ${DEFAULT_LIBDIR}/rerun/modules/*
             do
-               [[ -f $module/metadata ]] && _rerun_module_summary "$module"
+               [[ -f "$module/metadata" ]] && _rerun_module_summary "$module"
             done
         fi
     done
@@ -1269,21 +1286,21 @@ _rerun_commands_summary() {
     local -r directory=$1
     local -r module=$2
 
-    module_dir=$(rerun_module_exists "$module") || rerun_syntax_error "module not found: \"$module\""
-    echo $(rerun_color blue "Available commands in module, \"$module\":")
+    local -r module_dir=$(rerun_module_exists "$module") || rerun_syntax_error "module not found: \"$module\""
+    printf "%s\n" "$(rerun_color blue "Available commands in module, \"$module\":")"
     shopt -s nullglob # enable
-
+    local cmd_name metadata
     for cmd in $module_dir/commands/*/metadata
 	do
-        local cmd_name=$(basename $(dirname "$cmd"))
-        local metadata=$module_dir/commands/${cmd_name}/metadata
-        [[ -f "$metadata" ]] && cmd_desc=$(rerun_property_get $(dirname "$cmd") DESCRIPTION)
-        echo $(rerun_color bold "${cmd_name}: \"${cmd_desc}\"")
+        cmd_name=$(basename "$(dirname "$cmd")")
+        metadata=$module_dir/commands/${cmd_name}/metadata
+        [[ -f "$metadata" ]] && cmd_desc=$(rerun_property_get "$(dirname "$cmd")" DESCRIPTION)
+        printf "%s\n" "$(rerun_color bold "${cmd_name}: \"${cmd_desc}\"")"
         if [[ -d "$module_dir/commands/${cmd_name}" ]]
         then            
             #
             # List the command options
-            local -a options=( $(rerun_options $(dirname "$module_dir") "$module" "$cmd_name") )
+            local -a options=( $(rerun_options "$(dirname "$module_dir")" "$module" "$cmd_name") )
             [[ -z "${options:-}" ]] && continue
             for opt in "${options[@]}"
             do
@@ -1291,23 +1308,24 @@ _rerun_commands_summary() {
                 if [[ -r "$opt_metadata" ]] 
                 then
                 (   set +u
-                    argstring= summary=                  
+                    argstring="" summary=""
+                    # shellcheck source=/dev/null
                     . "$opt_metadata" ; # Read the option's metadata.                    
-                    [[ -n "${SHORT}" ]] && {                    
+                    if [[ -n "${SHORT}" ]]; then
                        argstring=$(printf ' --%s|-%s'  "$NAME" "$SHORT")
-                    } || {
+                    else
                        argstring=$(printf " --%s" "$NAME" )
-                    }	  
+                    fi  
                     [[ "$ARGUMENTS" == "true" ]] && {
                         # Lookup the default but set expand=false to not evalute possible variable.
                         DEFAULT=$(rerun_property_get "$module_dir/options/${opt}" DEFAULT false)
                         argstring=$(printf "%s <%s>" "$argstring" "$(rerun_color ul "${DEFAULT}")")
                     }
-                    [[ "$REQUIRED" != "true" ]] && {
+                    if [[ "$REQUIRED" != "true" ]]; then
                         summary=$(printf "[%s]: \"%s\"" "${argstring}" "$DESCRIPTION") 
-                    } || {
+                    else
                         summary=$(printf "%s: \"%s\"" "${argstring}" "$DESCRIPTION")
-                    }
+                    fi
                     echo -e "$PAD $summary"
                     set -u
                 )
@@ -1336,7 +1354,7 @@ while (( "$#" > 0 )); do
 	-h*|--h*)
         _rerun_banner
         ! rerun_option_usage
-        _rerun_examples $(basename "$0")
+        _rerun_examples "$(basename "$0")"
         exit 0
 	    ;;
     --banner)  _rerun_banner ; exit 0
@@ -1452,7 +1470,7 @@ fi
 # Read answer file and set positional parameters from them.
 if [[ -n "${ANSWERS:-}" && -f "${ANSWERS:-}" ]]
 then
-    eval set -- $@ $(_rerun_options_populate "$MODULE" "$COMMAND" "$ANSWERS")
+    eval set -- "$@" "$(_rerun_options_populate "$MODULE" "$COMMAND" "$ANSWERS")"
 fi
 
 
