fixed stubbs:add-option bug preventing short arg support.

diff --git a/rerun b/rerun
--- a/rerun
+++ b/rerun
@@ -16,7 +16,7 @@
 
 # The rerun version.
 
-RERUN_VERSION=1.3.3
+RERUN_VERSION=1.3.4
 
 # The default system install directories.
 
@@ -50,6 +50,9 @@ rerun() {
     command $RERUN -M $RERUN_MODULES "$@"
 }
 
+#
+# - - -
+#
 
 # rerun_color - Prints message in specified color using ansi codes.
 #
@@ -188,7 +191,7 @@ rerun_log_syslog() {
         printf >&2 'wrong # args: should be: rerun_log_syslog facility level command message\n'
         return 2
     }
-    local -r facility="$1" level="$2" command="${3:-rerun}" message="$4"
+    local -r facility="$1" level="$2" command="${3:-$(basename $0)}" message="$4"
 
     # map rerun_log level to syslog priority.
     local pri=
@@ -346,7 +349,7 @@ rerun_die() {
         (( frame++ )) || :; #ignore increment errors (i.e., errexit is set)
     done
 
-    echo >&2 $(rerun_log error "ERROR: $*")
+    rerun_log error "ERROR: $*" >&2
     exit ${exit_status:-1}
 }
 
