cleaned up code for better clarity and comment

diff --git a/modules/stubbs/templates/extract b/modules/stubbs/templates/extract
--- a/modules/stubbs/templates/extract
+++ b/modules/stubbs/templates/extract
@@ -1,21 +1,38 @@
 #!/bin/bash
 #
-# the self extracting rerun 
+# this is a self contained self extracting rerun 
 #
-export TMPDIR=`mktemp -d /tmp/selfextract.XXXXXX`
+
+# Function to print error message and exit
+die() { echo "ERROR: $* " ; exit 1 ; }
+
+# extracted payload goes in here
+export TMPDIR=`mktemp -d /tmp/rerun.bsx.XXXXXX` || die 
 
 ARCHIVE=`awk '/^__ARCHIVE_BELOW__/ {print NR + 1; exit 0; }' $0`
 
-tail -n+$ARCHIVE $0 | tar xz -C $TMPDIR
+# Extraction time!
+# - read lines from delimiter and pass to tar unarchive
+tail -n+$ARCHIVE $0 | tar xz -C $TMPDIR || die
 
-export CDIR=`pwd`
+# CWD and TMDIR are passed to launcher as env variables
+export CWD=`pwd`
 export TMPDIR
-cd $TMPDIR
-bash ./launcher $*
 
-cd $CDIR
+# Change directory to the temp directory
+cd $TMPDIR || die
+
+# Run the launcher !
+bash ./launcher $*
+RETVAL=$?
+
+# Go back to original working directory
+cd $CWD
+
+# Clean up after ourselves
 rm -rf $TMPDIR
 
-exit 0
+# Stop this script from executing before we reach the binary archive!
+exit ${RETVAL:=0}
 
 __ARCHIVE_BELOW__
diff --git a/modules/stubbs/templates/launcher b/modules/stubbs/templates/launcher
--- a/modules/stubbs/templates/launcher
+++ b/modules/stubbs/templates/launcher
@@ -4,25 +4,25 @@
 #
 
 # Function to print error message and exit
-die() {
-    echo "ERROR: $* " ; exit 1;
-}
+die() { echo "ERROR: $* " ; exit 1 ; }
 
 # Check for required environment variables 
-[ -z "${CDIR}" ] && die "CDIR not set" ;# current working directory
+[ -z "${CWD}" ] && die "CWD not set" ;# current working directory
 [ -z "${TMPDIR}" ] && die "TMPDIR not set" ;# archive artifacts 
 
-# Check the extracted artifact contents
+# Verify the extracted artifact contents
 [ -d ./rerun ] || die "rerun subdirectory not found"
-[ -d ./rerun/modules ] || "missing modules subdirectory"
+[ -d ./rerun/modules ] || die "missing modules subdirectory"
 [ -f ./rerun/rerun ] || die "missing rerun script"
-[ -x ./rerun/rerun ] || { chmod +x ./rerun || die ; }
+[ -x ./rerun/rerun ] || { chmod +x ./rerun || die "couldn't set rerun executable" ; }
 
+# set the module directory base
 export RERUN_MODULES=$TMPDIR/rerun/modules
 
-# move into the cwd directory
-cd $CDIR || die
+# move into the current working directory
+cd $CWD || die "couldn't change to cwd: $CWD"
 
+# launch it!
 exec $TMPDIR/rerun/rerun $*
 
 # Done
