Interactive prompt supplies current option values.
Update add-option to present current option metadata properties
in interactive mode.

Fixes #57

diff --git a/modules/stubbs/commands/add-option/script b/modules/stubbs/commands/add-option/script
--- a/modules/stubbs/commands/add-option/script
+++ b/modules/stubbs/commands/add-option/script
@@ -13,6 +13,14 @@
 # Source common function library
 . $RERUN_MODULE_DIR/lib/functions.sh || { echo >&2 "failed laoding function library" ; exit 1 ; }
 
+display_default() {
+    eval local var=\$$1
+    if [[ -n "$var" ]]
+    then  printf " (%s):" "$var" 
+    else  printf ":" 
+    fi
+}
+
 # Init the handler
 stubbs_init
 
@@ -89,7 +97,7 @@ done
 
 
 [ -z "$MODULE" ] && {
-    echo "Module: "
+    printf "Module: \n"
     select MODULE in $(rerun_modules $RERUN_MODULES);
     do
 	echo "You picked module $MODULE ($REPLY)"
@@ -98,11 +106,13 @@ done
 }
 
 # check the chosen module exists
-[ ! -f $RERUN_MODULES/$MODULE/metadata ] && rerun_die "module not found: $MODULE"
+[ ! -f $RERUN_MODULES/$MODULE/metadata ] && rerun_option_error "module not found: $MODULE"
 
 [ -z "$COMMAND" ] && {
-    echo "Command: "
-    select COMMAND in $(rerun_commands $RERUN_MODULES $MODULE);
+    commands=( $(rerun_commands $RERUN_MODULES $MODULE) )
+    [[ -z ${commands:-} ]] && rerun_die "No commands exist for module: $MODULE"
+    printf "Command: \n"
+    select COMMAND in ${commands[*]}
     do
 	echo "You picked command $COMMAND ($REPLY)"
 	break
@@ -111,35 +121,53 @@ done
 
 # Verify this command exists
 #
-[ -d $RERUN_MODULES/$MODULE/commands/$COMMAND ] || {
-    rerun_option_error "command not found: \""$MODULE:$COMMAND\"""
-}
+[ ! -d $RERUN_MODULES/$MODULE/commands/$COMMAND ] && rerun_option_error "command not found: \"$MODULE:$COMMAND\""
 
-# Post process the options
+
+# Was option argument specified?
 [ -z "$OPTION" ] && {
-    echo "Option: "
+    printf "Option: \n"
     read OPTION
 }
 
+# This option might already be declared.
+# Confirm the option declaration settings.
+if [[ -f $RERUN_MODULES/$MODULE/options/$OPTION/metadata ]]
+then
+    CURR_DESC=$(rerun_property_get $RERUN_MODULES/$MODULE/options/$OPTION DESCRIPTION)
+    CURR_REQ=$(rerun_property_get $RERUN_MODULES/$MODULE/options/$OPTION REQUIRED)
+    CURR_DEFAULT=$(rerun_property_get $RERUN_MODULES/$MODULE/options/$OPTION DEFAULT)
+    CURR_EXPORT=$(rerun_property_get $RERUN_MODULES/$MODULE/options/$OPTION EXPORT)
+fi
+# Confirm the description.
 [ -z "$DESC" ] && {
-    echo "Description: "
+    printf "Description%s\n" "$(display_default CURR_DESC)"
     read DESC
+    [[ -n "${CURR_DESC}" && -z "$DESC" ]] && DESC=${CURR_DESC}
 }
-
+# Confirm the option requirement.
 [ -z "$REQ" ] && {
-    echo "Required (true/false): "
+    printf "Required%s\n" "$(display_default CURR_REQ)"
     select REQ in true false;
-    do
-	break
+    do	break
     done
 }
 
-[ -z "$DEFAULT" ] && {
-    echo "Default: "
-    read DEFAULT
+# Confirm the option export requirement.
+[ -z "$EXPORT" ] && {
+    printf "Export%s\n" "$(display_default CURR_EXPORT)"
+    select EXPORT in true false;
+    do	break
+    done
+    [[ -n "${CURR_EXPORT}" && -z "$EXPORT" ]] && EXPORT=${CURR_EXPORT}
 }
 
-[ -z "$EXPORT" ] && EXPORT=false
+# Confirm the default value.
+[ -z "$DEFAULT" ] && {
+    printf "Default%s\n" "$(display_default CURR_DEFAULT)"
+    read DEFAULT
+    [[ -n "${CURR_DEFAULT}" && -z "$DEFAULT" ]] && DEFAULT=${CURR_DEFAULT}
+}
 
 # Generate metadata for new option
 mkdir -p  $RERUN_MODULES/$MODULE/options/$OPTION
@@ -164,18 +192,18 @@ echo "Wrote option metadata: $RERUN_MODULES/$MODULE/options/$OPTION/metadata"
 #
 # Update the command metadata.
 #
-commandOptions=( $(rerun_options $RERUN_MODULES $MODULE $COMMAND) )
+command_options=( $(rerun_options $RERUN_MODULES $MODULE $COMMAND) )
 # Check if this option has already been assigned.
-rerun_list_contains "$OPTION" "${commandOptions[*]}" || {
-    commandOptions=( ${commandOptions[*]} $OPTION )
+rerun_list_contains "$OPTION" "${command_options[*]}" || {
+    command_options=( ${command_options[*]} $OPTION )
 }
 
-commandMetadata=$RERUN_MODULES/$MODULE/commands/$COMMAND/metadata
+command_metadata=$RERUN_MODULES/$MODULE/commands/$COMMAND/metadata
 
 stubbs_command_options_write \
     $RERUN_MODULES/$MODULE $COMMAND \
-    "${commandOptions[*]}" || rerun_die "Failed generating command metadata"
-echo "Updated command metadata:  $commandMetadata"
+    "${command_options[*]}" || rerun_die "Failed generating command metadata"
+echo "Updated command metadata:  $command_metadata"
 
 
 #
@@ -197,10 +225,10 @@ INTERPRETER=$(. $RERUN_MODULES/$MODULE/metadata; echo ${INTERPRETER:-bash});
 [ -z "$RERUN_OPTIONS_SCRIPT" ] && {
     rerun_die "required metadata not found: RERUN_OPTIONS_SCRIPT"
 }
-optionsParserScript=$RERUN_MODULES/$MODULE/commands/$COMMAND/$RERUN_OPTIONS_SCRIPT
+options_parser=$RERUN_MODULES/$MODULE/commands/$COMMAND/$RERUN_OPTIONS_SCRIPT
 
 $RERUN_MODULE_DIR/lib/interpreters/$INTERPRETER/$RERUN_OPTIONS_GENERATOR \
-    $RERUN_MODULES $MODULE $COMMAND > $optionsParserScript || {
+    $RERUN_MODULES $MODULE $COMMAND > $options_parser || {
     rerun_die "Failed generating options parser."
 }
 
@@ -211,18 +239,18 @@ $RERUN_MODULE_DIR/lib/interpreters/$INTERPRETER/$RERUN_OPTIONS_GENERATOR \
     rerun_die "required metadata not found: RERUN_COMMAND_SCRIPT"
 }
 
-commandScript=$RERUN_MODULES/$MODULE/commands/$COMMAND/$RERUN_COMMAND_SCRIPT
-if [ -f "$commandScript" ]
+command_script=$RERUN_MODULES/$MODULE/commands/$COMMAND/$RERUN_COMMAND_SCRIPT
+if [ -f "$command_script" ]
 then
     stubbs_script_header \
-        $RERUN_MODULES/$MODULE $COMMAND > ${commandScript}.$$ || {
+        $RERUN_MODULES/$MODULE $COMMAND > ${command_script}.$$ || {
         rerun_die "Error updating command script header"
     }
-    mv $commandScript.$$ $commandScript || {
+    mv $command_script.$$ $command_script || {
         rerun_die "Error updating command script header"
     }
-    chmod +x $commandScript || rerun_die "Failed setting execute bit on command script."
-    echo "Updated command script header: $commandScript"
+    chmod +x $command_script || rerun_die "Failed setting execute bit on command script."
+    echo "Updated command script header: $command_script"
 fi
 
 # Done
