Refactored commands to use standard error handling
Fixes #95

diff --git a/modules/stubbs/commands/add-command/script b/modules/stubbs/commands/add-command/script
--- a/modules/stubbs/commands/add-command/script
+++ b/modules/stubbs/commands/add-command/script
@@ -1,22 +1,51 @@
 #!/usr/bin/env bash
 #
-# NAME
-#
-#   add-command
-#
-# DESCRIPTION
-#
-#   add command to module
-#
+#/ command: stubbs:add-command: "add a new command"
 #/ usage: stubbs:add-command  --command|-c <> --module|-m <> [-overwrite] [-template <>]
 
-# Source common function library
-. $RERUN_MODULE_DIR/lib/functions.sh || { echo >&2 "failed loading function library" ; exit 1 ; }
+# Load common functions
+# ---------------------
 
+# Load the function library for this module.
+# This loads rerun functions and those defined for @MODULE@.
+. $RERUN_MODULE_DIR/lib/functions.sh add-command || { 
+    echo >&2 "failed loading function library" ; exit 1 ; 
+}
+
+# Error handling
+# ---------------
+
+# This script is designed to _fail-fast_.
+
+# Trap errors and exit. The call to `rerun_die` will print the
+# the error message and exit with the error command exit status. 
+
+trap 'rerun_die $? "*** command failed: stubbs:add-command. ***"' ERR
+
+# Run [set] `nounset` to treat unset variables as errors. Set [pipefail]
+# so a pipeline return status is the value of the last 
+# (rightmost) command to exit with non-zero status.
+#
+# [set]: http://ss64.com/bash/set.html
+# [pipefail]: http://www.gnu.org/software/bash/manual/html_node/Pipelines.html
+
+set -o nounset -o pipefail
+
+
+# Command implementation
+# ----------------------
 
 # Init the handler
 stubbs_init 
 
+# Command variables
+# -----------------
+
+# This command script can access the following variables
+# declared by `rerun` or by the option parser function.
+
+#/ rerun-variables: RERUN, RERUN_VERSION, RERUN_MODULES, RERUN_MODULE_DIR
+#/ option-variables: COMMAND DESCRIPTION MODULE OVERWRITE TEMPLATE
 
 # Get the options
 while [ "$#" -gt 0 ]; do
@@ -31,7 +60,7 @@ while [ "$#" -gt 0 ]; do
 	    ;;
 	--description)
 	    rerun_option_check "$#" "$1"
-	    DESC="$2"
+	    DESCRIPTION="$2"
 	    shift
 	    ;;
 	-m|--module)
@@ -63,7 +92,7 @@ done
 
 # Post processes the options
 
-[ -z "$MODULE" ] && {
+[ -z "${MODULE:-}" ] && {
     echo "Module: "
     select MODULE in $(rerun_modules $RERUN_MODULES);
     do
@@ -72,14 +101,14 @@ done
     done
 }
 
-[ -z "$COMMAND" ] && {
+[ -z "${COMMAND:-}" ] && {
     echo "Command: "
     read COMMAND
 }
 
-[ -z "$DESC" ] && {
+[ -z "${DESCRIPTION:-}" ] && {
     echo "Description: "
-    read DESC
+    read DESCRIPTION
 }
 
 
@@ -106,10 +135,10 @@ RERUN_COMMAND_SCRIPT=$(rerun_property_get $INTERPRETER_LIB RERUN_COMMAND_SCRIPT)
 }
 
 
-[ -z "$TEMPLATE" ] && {
+[ -z "${TEMPLATE:-}" ] && {
     TEMPLATE=$INTERPRETER_LIB/$RERUN_COMMAND_SCRIPT
 }
-[ ! -f "$TEMPLATE" ] && {
+[ ! -f "${TEMPLATE:-}" ] && {
     rerun_syntax_error "command script template not found: \"$TEMPLATE\""
 }
 
@@ -117,10 +146,10 @@ RERUN_COMMAND_SCRIPT=$(rerun_property_get $INTERPRETER_LIB RERUN_COMMAND_SCRIPT)
 CMD_SCRIPT=$RERUN_MODULES/$MODULE/commands/$COMMAND/$(basename $RERUN_COMMAND_SCRIPT)
 
 # Generate a boiler plate implementation
-[ ! -f $CMD_SCRIPT -o -n "$OVERWRITE" ] && {
+[ ! -f $CMD_SCRIPT -o -n "${OVERWRITE:-}" ] && {
     sed -e "s/@COMMAND@/$COMMAND/g" \
 	-e "s/@MODULE@/$MODULE/g" \
-	-e "s,@DESCRIPTION@,$DESC,g" \
+	-e "s,@DESCRIPTION@,$DESCRIPTION,g" \
 	-e "s/@INTERPRETER@/$INTERPRETER/g" \
     -e "s/@VARIABLES@/$VARIABLES/g" \
 	$TEMPLATE > $CMD_SCRIPT || rerun_die "Failed generating stub comand script"
@@ -130,7 +159,7 @@ CMD_SCRIPT=$RERUN_MODULES/$MODULE/commands/$COMMAND/$(basename $RERUN_COMMAND_SC
 
 # Generate a unit test script
 mkdir -p $RERUN_MODULES/$MODULE/tests || rerun_die "failed creating tests directory"
-[ ! -f $RERUN_MODULES/$MODULE/tests/$COMMAND-1-test.sh -o -n "$OVERWRITE" ] && {
+[ ! -f $RERUN_MODULES/$MODULE/tests/$COMMAND-1-test.sh -o -n "${OVERWRITE:-}" ] && {
     sed -e "s/@MODULE@/$MODULE/g" \
 	-e "s/@COMMAND@/$COMMAND/g" \
 	-e "s/@INTERPRETER@/$INTERPRETER/g" \
@@ -139,7 +168,7 @@ mkdir -p $RERUN_MODULES/$MODULE/tests || rerun_die "failed creating tests direct
 	$RERUN_MODULE_DIR/templates/test.roundup > $RERUN_MODULES/$MODULE/tests/$COMMAND-1-test.sh || rerun_die
     echo "Wrote test script: $RERUN_MODULES/$MODULE/tests/$COMMAND-1-test.sh"
 }
-[ ! -f $RERUN_MODULES/$MODULE/tests/functions.sh -o -n "$OVERWRITE" ] && {
+[ ! -f $RERUN_MODULES/$MODULE/tests/functions.sh -o -n "${OVERWRITE:-}" ] && {
     sed -e "s/@MODULE@/$MODULE/g" \
 	$RERUN_MODULE_DIR/templates/test.functions.sh > $RERUN_MODULES/$MODULE/tests/functions.sh || rerun_die "Failed generating test functions library."
 }
@@ -151,7 +180,7 @@ cat <<EOF
 # generated by stubbs:add-command
 # $(date)
 NAME=$COMMAND
-DESCRIPTION="$DESC"
+DESCRIPTION="$DESCRIPTION"
 OPTIONS=
 EOF
 ) > $RERUN_MODULES/$MODULE/commands/$COMMAND/metadata || rerun_die "Failed creating command metadata"
diff --git a/modules/stubbs/commands/add-module/script b/modules/stubbs/commands/add-module/script
--- a/modules/stubbs/commands/add-module/script
+++ b/modules/stubbs/commands/add-module/script
@@ -1,19 +1,45 @@
 #!/usr/bin/env bash
 #
-# NAME
-#
-#   add-module
-#
-# DESCRIPTION
-#
-#   add a new module
-#
-#/ usage: stubbs:add-module --language|-l <sh> --module|-m <> --description <>
+#/ command: stubbs:add-module: "add a new module"
+#/ usage: stubbs:add-module --interpreter|-i <bash> --module|-m <> --description <>
 
-# Source common function library
-. $RERUN_MODULE_DIR/lib/functions.sh || { echo >&2 "failed loading function library" ; exit 1 ; }
+# Load common functions
+# ---------------------
+
+# Load the function library for this module.
+# This loads rerun functions and those defined for stubbs.
+. $RERUN_MODULE_DIR/lib/functions.sh add-module || { 
+    echo >&2 "failed loading function library" ; exit 1 ; 
+}
+
+# Error handling
+# ---------------
+
+# This script is designed to _fail-fast_.
+
+# Trap errors and exit. The call to `rerun_die` will print the
+# the error message and exit with the error command exit status. 
+
+trap 'rerun_die $? "*** command failed: stubbs:add-module. ***"' ERR
+
+# Run [set] `nounset` to treat unset variables as errors. Set [pipefail]
+# so a pipeline return status is the value of the last 
+# (rightmost) command to exit with non-zero status.
+#
+# [set]: http://ss64.com/bash/set.html
+# [pipefail]: http://www.gnu.org/software/bash/manual/html_node/Pipelines.html
+
+set -o nounset -o pipefail
+
+
+# Command implementation
+# ----------------------
 
 stubbs_init
+
+#/ rerun-variables: RERUN, RERUN_VERSION, RERUN_MODULES, RERUN_MODULE_DIR
+#/ option-variables: INTERPRETER MODULE DESCRIPTION
+
 
 # Get the options
 while [ "$#" -gt 0 ]; do
@@ -33,7 +59,7 @@ while [ "$#" -gt 0 ]; do
 	    ;;
 	--description)
 	    rerun_option_check "$#" "$1"
-	    DESC="$2"
+	    DESCRIPTION="$2"
 	    shift
 	    ;;
         # unknown option
@@ -49,14 +75,14 @@ while [ "$#" -gt 0 ]; do
 done
 
 # Post processes the options
-[ -z "$MODULE" ] && {
+[ -z "${MODULE:-}" ] && {
     echo "Module name: "
     read MODULE
 }
 
-[ -z "$DESC" ] && {
+[ -z "${DESCRIPTION:-}" ] && {
     echo "Module description: "
-    read DESC
+    read DESCRIPTION
 }
 
 # Set bash as the default interpreter.
@@ -87,7 +113,7 @@ cat <<EOF
 # generated by stubbs:add-module
 # $(date)
 NAME=$MODULE
-DESCRIPTION="$DESC"
+DESCRIPTION="$DESCRIPTION"
 INTERPRETER="$INTERPRETER"
 VERSION=
 REQUIRES=
@@ -98,7 +124,7 @@ EOF
 # Give it the beginnings of a function library.
 # Replace the word "@MODULE@" with the module's given name.
 sed -e "s/@MODULE@/$MODULE/g" \
-	-e "s,@DESCRIPTION@,$DESC,g" \
+	-e "s,@DESCRIPTION@,$DESCRIPTION,g" \
 	-e "s/@INTERPRETER@/$INTERPRETER/g" \
     "$INTERPRETER_LIB/$RERUN_FUNCTION_LIB" \
     > "$RERUN_MODULES/$MODULE/lib/$(basename $RERUN_FUNCTION_LIB)" || {
diff --git a/modules/stubbs/commands/add-option/script b/modules/stubbs/commands/add-option/script
--- a/modules/stubbs/commands/add-option/script
+++ b/modules/stubbs/commands/add-option/script
@@ -2,16 +2,41 @@
 #
 # NAME
 #
-#   add-option
-#
-# DESCRIPTION
-#
-#   add a command option
-#
+#/ command: stubbs:add-option: "add a command option"
 #/ usage: stubbs:add-option [--arg <false>] --command|-c <> [--default|-d <>] --description <> [--export|-e <false>] [--long <>] --module|-m <> --option|-o <> [--required <false>] [--short <>]
 
-# Source common function library
-. $RERUN_MODULE_DIR/lib/functions.sh || { echo >&2 "failed laoding function library" ; exit 1 ; }
+# Load common functions
+# ---------------------
+
+# Load the function library for this module.
+# This loads rerun functions and those defined for stubbs.
+. $RERUN_MODULE_DIR/lib/functions.sh || { 
+    echo >&2 "failed laoding function library" ; exit 1 ; 
+}
+
+# Error handling
+# ---------------
+
+# This script is designed to _fail-fast_.
+
+# Trap errors and exit. The call to `rerun_die` will print the
+# the error message and exit with the error command exit status. 
+
+trap 'rerun_die $? "*** command failed: stubbs:add-option. ***"' ERR
+
+# Run [set] `nounset` to treat unset variables as errors. Set [pipefail]
+# so a pipeline return status is the value of the last 
+# (rightmost) command to exit with non-zero status.
+#
+# [set]: http://ss64.com/bash/set.html
+# [pipefail]: http://www.gnu.org/software/bash/manual/html_node/Pipelines.html
+
+set -o nounset -o pipefail
+
+
+# Command implementation
+# ----------------------
+
 
 display_default() {
     eval local var=\$$1
@@ -37,7 +62,7 @@ while [ "$#" -gt 0 ]; do
 	    ;;
 	--desc*)
 	    rerun_option_check "$#" "$1"
-	    DESC="$2"
+	    DESCRIPTION="$2"
 	    shift
 	    ;;
 	-c|--command)
@@ -131,7 +156,7 @@ done
 }
 
 # Was option argument specified?
-[ -z "$OPTION" ] && {
+[ -z "${OPTION:-}" ] && {
     printf "Option: \n"
     read OPTION
 }
@@ -149,13 +174,13 @@ then
         $RERUN_MODULES/$MODULE/options/$OPTION/metadata)
 fi
 # Confirm the description.
-[ -z "$DESC" ] && {
+[ -z "${DESCRIPTION:-}" ] && {
     printf "Description%s\n" "$(display_default CURR_DESC)"
-    read DESC
-    [[ -n "${CURR_DESC}" && -z "$DESC" ]] && DESC="${CURR_DESC}"
+    read DESCRIPTION
+    [[ -n "${CURR_DESC:-}" && -z "$DESCRIPTION" ]] && DESCRIPTION="${CURR_DESC}"
 }
 # Confirm the option requirement.
-[ -z "$REQ" ] && {
+[ -z "${REQ:-}" ] && {
     printf "Required%s\n" "$(display_default CURR_REQ)"
     select REQ in true false;
     do	break
@@ -163,23 +188,23 @@ fi
 }
 
 # Confirm the option export requirement.
-[ -z "$EXPORT" ] && {
+[ -z "${EXPORT:-}" ] && {
     printf "Export%s\n" "$(display_default CURR_EXPORT)"
     select EXPORT in true false;
     do	break
     done
-    [[ -n "${CURR_EXPORT}" && -z "$EXPORT" ]] && EXPORT=${CURR_EXPORT}
+    [[ -n "${CURR_EXPORT:-}" && -z "$EXPORT" ]] && EXPORT=${CURR_EXPORT}
 }
 
 # Confirm the default value.
-[ -z "$DEFAULT" ] && {
+[ -z "${DEFAULT:-}" ] && {
     printf "Default%s\n" "$(display_default CURR_DEFAULT)"
     read DEFAULT
-    [[ -n "${CURR_DEFAULT}" && -z "$DEFAULT" ]] && DEFAULT="${CURR_DEFAULT}"
+    [[ -n "${CURR_DEFAULT:-}" && -z "$DEFAULT" ]] && DEFAULT="${CURR_DEFAULT}"
 }
 
 # If short is specified, check it's not already used.
-[ -n "$SHORT" ] && {
+[ -n "${SHORT:-}" ] && {
     options=$(stubbs_options_with_short "$RERUN_MODULES/$MODULE" $SHORT)
     [ -n "$options" ] && {
         rerun_die "-${SHORT} already used by option: $options"
@@ -194,10 +219,10 @@ mkdir -p  $RERUN_MODULES/$MODULE/options/$OPTION
 # generated by stubbs:add-option
 # $(date)
 NAME=$OPTION
-DESCRIPTION="$DESC"
+DESCRIPTION="$DESCRIPTION"
 ARGUMENTS=${ARGS:-true}
 REQUIRED=${REQ:-true}
-SHORT=${SHORT}
+SHORT=${SHORT:-}
 LONG=${LONG:-$OPTION}
 DEFAULT=$DEFAULT
 EXPORT=$EXPORT
@@ -214,7 +239,10 @@ echo "Wrote option metadata: $RERUN_MODULES/$MODULE/options/$OPTION/metadata"
 command_options=( $(rerun_options $RERUN_MODULES $MODULE $COMMAND) )
 # Add this OPTION to the list if it is not yet assigned.
 rerun_list_contains "$OPTION" "${command_options[@]:-}" || {
-    command_options=( ${command_options[*]} $OPTION )
+    if [[ -z "${command_options:-}" ]]
+    then command_options=( $OPTION ) 
+    else command_options=( ${command_options[*]} $OPTION )
+    fi
 }
 
 command_metadata=$RERUN_MODULES/$MODULE/commands/$COMMAND/metadata
diff --git a/modules/stubbs/commands/archive/script b/modules/stubbs/commands/archive/script
--- a/modules/stubbs/commands/archive/script
+++ b/modules/stubbs/commands/archive/script
@@ -1,28 +1,51 @@
 #!/usr/bin/env bash
 #
-# NAME
-#
-#   archive
-#
-# DESCRIPTION
-#
-#   Build a self extracting archive
-#
+# command: stubbs:archive: "Build a self extracting archive"
 #/ usage: rerun stubbs:archive [ --file|-f <>] [ --format|-f <bin>]  --modules <*> [ --release|-r <1>] [ --version|-v <>] 
 
-# Source common function library
-. $RERUN_MODULE_DIR/lib/functions.sh || { echo >&2 "failed laoding function library" ; exit 1 ; }
+
+# Load common functions
+# ---------------------
+
+# Load the function library for this module.
+# This loads rerun functions and those defined for stubbs.
+. $RERUN_MODULE_DIR/lib/functions.sh || { 
+    echo >&2 "failed laoding function library" ; exit 1 ; 
+}
 
 # Parse the command options
 [ -r $RERUN_MODULE_DIR/commands/archive/options.sh ] && {
   . $RERUN_MODULE_DIR/commands/archive/options.sh
 }
 
+# Error handling
+# ---------------
+
+# This script is designed to _fail-fast_.
+
+# Trap errors and exit. The call to `rerun_die` will print the
+# the error message and exit with the error command exit status. 
+
+trap 'rerun_die $? "*** command failed: stubbs:archive. ***"' ERR
+
+# Run [set] `nounset` to treat unset variables as errors. Set [pipefail]
+# so a pipeline return status is the value of the last 
+# (rightmost) command to exit with non-zero status.
+#
+# [set]: http://ss64.com/bash/set.html
+# [pipefail]: http://www.gnu.org/software/bash/manual/html_node/Pipelines.html
+
+set -o nounset -o pipefail
+
+
+# Command implementation
+# ----------------------
+
 buildbinarchive() {
   CWD=$(pwd); #remember current working directory.
 
   # Check if file option was specified and if not set it to rerun.bin.
-  [ -z "${FILE}"  ] && FILE=rerun.bin 
+  [ -z "${FILE:-}"  ] && FILE=rerun.bin 
 
   # Prepend curren working directory if relative file path.
   [[ ${FILE} == "/"* ]] || FILE=$CWD/$FILE
@@ -30,7 +53,7 @@ buildbinarchive() {
   [ ! -d $(dirname ${FILE}) ] && rerun_option_error "directory not found: $(dirname ${FILE})"
 
   # Default version to blank if unspecified.
-  [ -z "${VERSION}" ] && VERSION=
+  [ -z "${VERSION:-}" ] && VERSION=
 
   # create a work directory the archive content
   export PAYLOAD=`mktemp -d /tmp/rerun.stubbs:archive.XXXXXX` || rerun_die
diff --git a/modules/stubbs/commands/docs/script b/modules/stubbs/commands/docs/script
--- a/modules/stubbs/commands/docs/script
+++ b/modules/stubbs/commands/docs/script
@@ -1,13 +1,6 @@
 #!/usr/bin/env bash
 #
-# NAME
-#
-#   docs
-#
-# DESCRIPTION
-#
-#   generate the docs
-#
+#/ command: stubbs:docs: "generate the docs"
 #/ usage: stubbs:docs --module|-m <>
 
 
@@ -17,7 +10,29 @@
 }
 
 # Source common function library
-. $RERUN_MODULE_DIR/lib/functions.sh || { echo >&2 "failed loading function library" ; exit 1 ; }
+. $RERUN_MODULE_DIR/lib/functions.sh || { 
+    echo >&2 "failed loading function library" ; exit 1 ; 
+}
+
+
+# Error handling
+# ---------------
+
+# This script is designed to _fail-fast_.
+
+# Trap errors and exit. The call to `rerun_die` will print the
+# the error message and exit with the error command exit status. 
+
+trap 'rerun_die $? "*** command failed: stubbs:docs. ***"' ERR
+
+# Run [set] `nounset` to treat unset variables as errors. Set [pipefail]
+# so a pipeline return status is the value of the last 
+# (rightmost) command to exit with non-zero status.
+#
+# [set]: http://ss64.com/bash/set.html
+# [pipefail]: http://www.gnu.org/software/bash/manual/html_node/Pipelines.html
+
+set -o nounset -o pipefail
 
 rerun_module_metadata() {
 	local FIELD=$(echo $1|tr "[:lower:]" "[:upper:]")
diff --git a/modules/stubbs/commands/rm-option/script b/modules/stubbs/commands/rm-option/script
--- a/modules/stubbs/commands/rm-option/script
+++ b/modules/stubbs/commands/rm-option/script
@@ -1,17 +1,37 @@
 #!/usr/bin/env bash
 #
-# NAME
-#
-#   rm-option
-#
-# DESCRIPTION
-#
-#   remove a command option
-#
+#/ command: stubbs:rm-option: "remove a command option"
 #/ usage: stubbs:rm-option --command|-c <> --module|-m <> --option|-o <>
 
-# Source common function library
-. $RERUN_MODULE_DIR/lib/functions.sh || { echo >&2 "failed laoding function library" ; exit 1 ; }
+# Load common functions
+# ---------------------
+
+# Load the function library for this module.
+# This loads rerun functions and those defined for stubbs.
+
+. $RERUN_MODULE_DIR/lib/functions.sh || { 
+    echo >&2 "failed laoding function library" ; exit 1 ; 
+}
+
+
+# Error handling
+# ---------------
+
+# This script is designed to _fail-fast_.
+
+# Trap errors and exit. The call to `rerun_die` will print the
+# the error message and exit with the error command exit status. 
+
+trap 'rerun_die $? "*** command failed: stubbs:rm-option. ***"' ERR
+
+# Run [set] `nounset` to treat unset variables as errors. Set [pipefail]
+# so a pipeline return status is the value of the last 
+# (rightmost) command to exit with non-zero status.
+#
+# [set]: http://ss64.com/bash/set.html
+# [pipefail]: http://www.gnu.org/software/bash/manual/html_node/Pipelines.html
+
+set -o nounset -o pipefail
 
 
 # Init the handler
@@ -77,7 +97,7 @@ done
     done
 }
 
-[ -z "$OPTION" ] && {
+[ -z "${OPTION:-}" ] && {
     echo "Option: "
     read OPTION
 }
@@ -101,7 +121,7 @@ command_options=( $(rerun_list_remove $OPTION $command_options_assignments) )
 
 stubbs_command_options_write \
     $RERUN_MODULES/$MODULE $COMMAND \
-    "${command_options[*]}" || rerun_die "Failed generating command metadata"
+    "${command_options[*]:-}" || rerun_die "Failed generating command metadata"
 echo "Updated command metadata:  $command_metadata"
 
 
diff --git a/modules/stubbs/commands/test/script b/modules/stubbs/commands/test/script
--- a/modules/stubbs/commands/test/script
+++ b/modules/stubbs/commands/test/script
@@ -1,17 +1,42 @@
 #!/usr/bin/env bash
 #
-# NAME
-#
-#   test
-#
-# DESCRIPTION
-#
-#   run module test scripts
-#
+#/ command: stubbs:test: "run module test scripts"
 #/ usage: stubbs:test --module|-m <> [--plan|-p <*>] [--logs <>] 
 
-# Source common function library
-. $RERUN_MODULE_DIR/lib/functions.sh || { echo >&2 "failed loading function library" ; exit 1 ; }
+
+# Load common functions
+# ---------------------
+
+# Load the function library for this module.
+# This loads rerun functions and those defined for stubbs.
+. $RERUN_MODULE_DIR/lib/functions.sh || { 
+    echo >&2 "failed loading function library" ; exit 1 ; 
+}
+
+
+# Error handling
+# ---------------
+
+# This script is designed to _fail-fast_.
+
+# Trap errors and exit. The call to `rerun_die` will print the
+# the error message and exit with the error command exit status. 
+
+trap 'rerun_die $? "*** command failed: stubbs:test. ***"' ERR
+
+# Run [set] `nounset` to treat unset variables as errors. Set [pipefail]
+# so a pipeline return status is the value of the last 
+# (rightmost) command to exit with non-zero status.
+#
+# [set]: http://ss64.com/bash/set.html
+# [pipefail]: http://www.gnu.org/software/bash/manual/html_node/Pipelines.html
+
+set -o nounset -o pipefail
+
+
+# Command implementation
+# ----------------------
+
 
 # init the handler
 stubbs_init
@@ -50,8 +75,8 @@ while [ "$#" -gt 0 ]; do
     shift
 done
 
-[ -z "$MODULE" ] &&  { rerun_option_error "missing required option: --module"; }
-[ -z "$PLAN" ] && PLAN="*"
+[ -z "${MODULE:-}" ] &&  { rerun_option_error "missing required option: --module"; }
+[ -z "${PLAN:-}" ] && PLAN="*"
 
 if [ ! -d "$RERUN_MODULES/$MODULE/tests" ]
 then
@@ -71,7 +96,7 @@ echo "========================================================="
     export RERUN_MODULES=$RERUN_MODULES
 
     # Export the answers file
-    export ANSWERS=$ANSWERS
+    export ANSWERS=${ANSWERS:-}
 
     # Roundup likes to run relative
     cd $RERUN_MODULES/$MODULE/tests
