Consolidate function loading.
Combine loading the rerun, module, and options function loads.

Fixes #91

diff --git a/modules/stubbs/lib/interpreters/bash/templates/script b/modules/stubbs/lib/interpreters/bash/templates/script
--- a/modules/stubbs/lib/interpreters/bash/templates/script
+++ b/modules/stubbs/lib/interpreters/bash/templates/script
@@ -1,36 +1,69 @@
 #!/usr/bin/env bash
-#
-#/ command: @MODULE@:@COMMAND@: "@DESCRIPTION@"
-#
-#/ usage: rerun @MODULE@:@COMMAND@ [options]
-#
-#/ rerun env variables: RERUN, RERUN_VERSION, RERUN_MODULES, RERUN_MODULE_DIR
-#/ option variables: @VARIABLES@
 
-# Read module function library.
-. $RERUN_MODULE_DIR/lib/functions.sh || { 
+# To implement this command, edit the "Command implementation" section below. 
+
+# Command usage
+# -------------
+
+# This script is the implementation for the @MODULE@:@COMMAND@ command.
+# Comments prefixed with `#/` are managed by stubbs.
+# The `command` and `usage` comments describe the command
+# and show its options.
+# 
+#/ command: @MODULE@:@COMMAND@: "@DESCRIPTION@"
+#/ usage: rerun @MODULE@:@COMMAND@ [options]
+
+# Load common functions
+# ---------------------
+
+# Load the function library for this module.
+# This loads rerun functions and those defined for @MODULE@.
+. $RERUN_MODULE_DIR/lib/functions.sh @COMMAND@ || { 
   echo >&2 "Failed loading function library." ; exit 1 ; 
 }
 
 # Error handling
 # ---------------
-# * Trap calls `rerun_die` with standard message.
-# * Exit upon command errors or accessing unset variables.
-#   * See [set](http://ss64.com/bash/set.html)
+
+# This script is designed to _fail-fast_.
+
+# Trap errors and exit. The call to `rerun_die` will print the
+# the error message and exit with the error command exit status. 
+
 trap 'rerun_die $? "*** command failed: @MODULE@:@COMMAND@. ***"' ERR
+
+# Run [set] `nounset` to treat unset variables as errors. Set [pipefail]
+# so a pipeline return status is the value of the last 
+# (rightmost) command to exit with non-zero status.
+#
+# [set]: http://ss64.com/bash/set.html
+# [pipefail]: http://www.gnu.org/software/bash/manual/html_node/Pipelines.html
+
 set -o nounset -o pipefail
 
-# Parse the command options.
-[[ -r $RERUN_MODULE_DIR/commands/@COMMAND@/options.sh ]] && {
-    . $RERUN_MODULE_DIR/commands/@COMMAND@/options.sh || rerun_die "Failed loading options parser."
-    rerun_options_parse "$@"
-}
+# Command variables
+# -----------------
+
+# This command script can access the following variables
+# declared by `rerun` or by the option parser function.
+
+#/ rerun env variables: RERUN, RERUN_VERSION, RERUN_MODULES, RERUN_MODULE_DIR
+#/ option variables: @VARIABLES@
+
+# The `rerun_options_parse` function processes the command line
+# arguments. Each accepted command line flag results in setting 
+# one the corresponding option variables.
+
+rerun_options_parse "$@"
 
 
-# ------------------------------
-# Your implementation goes here.
-# ------------------------------
+# Command implementation
+# ----------------------
 
+# - - -
+# Put the command implementation here.
+# - - -
+
+# Done. Exit with last command exit status.
 exit $?
 
-# Done
